# Generated by Django 3.2 on 2022-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_author_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='designation',
            field=models.CharField(choices=[('writer', 'writer'), ('editor', 'editor'), ('senior-editor', 'senior-editor')], default='writer', max_length=20),
        ),
    ]
