# Generated by Django 3.2 on 2022-09-07 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220906_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
