# Generated by Django 3.2 on 2022-09-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220907_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
