# Generated by Django 3.2 on 2022-09-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_author_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='name',
        ),
    ]
