# Generated by Django 3.2 on 2022-09-09 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_name_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='author/'),
            preserve_default=False,
        ),
    ]
