# Generated by Django 3.2 on 2022-09-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_alter_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='authentication.user'),
            preserve_default=False,
        ),
    ]
