# Generated by Django 3.2 on 2023-01-03 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_author_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='uploaded_by',
        ),
    ]
