# Generated by Django 3.2 on 2023-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_author_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
